# Generated by Django 5.2.5 on 2025-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myERP', '0005_studentprofile_email_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='images/avtar.png', upload_to='images/'),
        ),
    ]
