# Generated by Django 5.2.5 on 2025-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myERP', '0006_alter_studentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='images/avatar.png', upload_to='images/'),
        ),
    ]
