# Generated by Django 5.2.5 on 2025-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myERP', '0007_alter_studentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
