# Generated by Django 5.2.5 on 2025-11-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myERP', '0008_alter_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
    ]
