# Generated by Django 5.2.5 on 2025-12-13 14:16

import myERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myERP', '0010_studentprofile_about_me_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/avatar.png', null=True, upload_to=myERP.models.user_profile_image_path),
        ),
    ]
